force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <label>Order</label>
    <nameField>
        <displayFormat>Order-{0000}</displayFormat>
        <label>Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <label>Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product__c/fields/Family__c.field-meta.xml
<CustomField>
    <fullName>Family__c</fullName>
    <label>Family</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Electronics</fullName>
            </value>
            <value>
                <fullName>Food</fullName>
            </value>
            <value>
                <fullName>Clothes</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Family__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Laptop</fullName>
            </value>
            <value>
                <fullName>PC</fullName>
            </value>
            <value>
                <fullName>Phone</fullName>
            </value>
            <value>
                <fullName>Drink</fullName>
            </value>
            <value>
                <fullName>Pizza</fullName>
            </value>
            <value>
                <fullName>Burger</fullName>
            </value>
            <value>
                <fullName>Dress</fullName>
            </value>
            <value>
                <fullName>Shoes</fullName>
            </value>
            <value>
                <fullName>Skirt</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/OrderManagerTest.cls
@isTest
private class OrderManagerTest {
    @TestSetup
    static void setup(){
        List<SObject> records = new List<SObject>();

        Account account = new Account(Name='testAcc');
        records.add(account);

        Product__c product = new Product__c(
            Name      = 'IPhone XR',
            Price__c  = 500,
            Family__c = 'Electronics',
            Type__c   = 'Phone'
        );

        Product__c product2 = new Product__c(
            Name      = 'IPhone X',
            Price__c  = 400,
            Family__c = 'Electronics',
            Type__c   = 'Phone'
        );
        records.add(product);
        records.add(product2);

        insert records;    
    }

    @isTest
    private static void createOrderTest() {
        Account account = [SELECT Id FROM Account LIMIT 1];
        List<Product__c> products = [SELECT Id, Price__c FROM Product__c];
        
        OrderManager.OrderWrapper orderWrapper = new OrderManager.OrderWrapper();
        orderWrapper.accountId  = account.Id;
        orderWrapper.orderItems = new List<OrderManager.OrderItemWrapper>();

        OrderManager.OrderItemWrapper orderItemWrapper = new OrderManager.OrderItemWrapper();
        orderItemWrapper.orderId   = '';
        orderItemWrapper.productId = products[0].Id;
        orderItemWrapper.quantity  = 4;
        orderItemWrapper.price     = products[0].Price__c;


        OrderManager.OrderItemWrapper orderItemWrapper1 = new OrderManager.OrderItemWrapper();
        orderItemWrapper1.orderId   = '';
        orderItemWrapper1.productId = products[1].Id;
        orderItemWrapper1.quantity  = 1;
        orderItemWrapper1.price     = products[1].Price__c;

        orderWrapper.orderItems.add(orderItemWrapper);
        orderWrapper.orderItems.add(orderItemWrapper1);
        
        String orderJSON = JSON.serialize(orderWrapper);

        OrderManager.createOrder(orderJSON);

        List<Order__c> orders = [
            SELECT Id, AccountId__c, TotalProductCount__c, TotalPrice__c 
            FROM Order__c
        ];

        System.assertEquals(1, orders.size());
        System.assertEquals(5, orders[0].TotalProductCount__c);
        System.assertEquals(2400, orders[0].TotalPrice__c);
    }
}